### ISSUE TITLE
generate_training_set.py for CircuitNet-N28 is not working.

### ISSUE THREAD

**Issue by invincible-28** [circuitnet/CircuitNet#41]
Is the "generate_training_set.py" script in the Google Drive (https://drive.google.com/drive/folders/1Xp2y29Le6Doo3meKhTZClVwxG_7z2QuF) for CircuitNet-N28 outdated? Because I am getting this error, after decompressing the routability features when trying to generate the training dataset for the task DRC:

processing 9 files
Process Process-1:
Traceback (most recent call last):
  File "../python3/3.10.6/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "../python3/3.10.6/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "../CircuitNet-main/CircuitNet-N28/preprocess_scripts/generate_training_set.py", line 60, in pack_data
    feature = np.load(os.path.join(args.data_path, feature_name, name))
  File "../python3/3.10.6/lib/python3.10/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
NotADirectoryError: [Errno 20] Not a directory: '../CircuitNet-main/CircuitNet-N28/routability_features_decompressed/macro_region/macro_region'

**Comment by apri0426** [comment]
It is not outdated, please confirm the paths in the error do exist.
